# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
    run:
    # setup-miniconda needs this as the default shell config doesn’t pick up its env changes
    shell: bash -el {0}

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environmentMIDAS.yml
    - name: Install dependencies
      run: |
        echo conda $PATH
        conda install pytest
        conda env list
    - name: Test with pytest
      run: |
        cd ${GITHUB_WORKSPACE}/midas/testing
        pytest
