# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environmentMIDAS.yml
    - name: Install dependencies
      run: |
        echo conda $PATH
        conda install pytest
        conda env list
        ls /usr/share/miniconda/envs/test/bin ⁠
      shell: bash -el {0}
    - name: Test with pytest
      run: |
        cd ${GITHUB_WORKSPACE}/midas/testing
        pytest
      shell: bash -el {0}
